export const documentationSections = [
  ['dashboard', 'Dashboard', 'Overview', 'See account health and trading performance at a glance.'],
  ['add-trade', 'Add Trade', 'Trade Entry', 'Create clean trade records manually, from files, or from supported import flows.'],
  ['journal', 'Trade Journal', 'Journal', 'Document every trade with context, screenshots, notes and review tags.'],
  ['trade-detail', 'Trade Detail', 'Trade View', 'Open one trade deeply and inspect the full decision from entry to exit.'],
  ['day-review', 'Day Review', 'Daily Review', 'Turn a trading day into one clear lesson before the next session.'],
  ['analytics', 'Performance Analytics', 'Analytics', 'Turn trading history into patterns, weaknesses and improvement decisions.'],
  ['replay', 'Replay And Backtest', 'Replay', 'Practice historical market decisions before risking live capital.'],
  ['broker-connection', 'Broker Connection', 'Connections', 'Understand supported sync and import flows without exposing private secrets.'],
  ['brokers', 'Broker Coverage', 'Brokers', 'Compare brokers, accounts, exchanges and markets cleanly.'],
  ['economic-calendar', 'Economic Calendar', 'Calendar', 'Plan around scheduled market-moving events and session risk.'],
  ['news', 'Market News', 'News', 'Use market headlines as trading context, not emotional noise.'],
  ['settings-profile', 'Settings And Profile', 'Account', 'Manage preferences, profile details and display choices safely.'],
  ['privacy-security', 'Privacy And Security', 'Safety', 'Keep sensitive trading and account information protected across the workflow.']
].map(([slug, label, eyebrow, title]) => ({
  id: `docs-${slug}`,
  slug,
  label,
  eyebrow,
  title,
  intro: `${label} documentation explains what the feature is for, when a trader should use it, and how it connects with the rest of the Entrack review workflow.`,
  points: [
    `Use ${label} to keep the trading workflow organized and repeatable.`,
    'Review only the information needed for decisions and learning.',
    'Connect this module with journal notes, analytics and daily review where relevant.',
    'Keep the interface focused so the trader can scan quickly and act deliberately.'
  ],
  workflow: `${label} should be used as part of a calm review process: open the page, check the relevant records, write or inspect context, then move to the next action with a clear reason.`,
  deepDive: [
    `${label} is part of the larger trading review system rather than a standalone decorative page.`,
    `The purpose of this page is to make ${eyebrow.toLowerCase()} easier to understand during real trading routines.`,
    'A trader should be able to open it and know what action is expected next.',
    'The page should support review, preparation, correction and repeatable decision-making.',
    'Important information should be structured in sections instead of being scattered across the app.',
    'The design should stay calm because traders often review performance after stressful sessions.',
    'The content should help users understand what the feature does without exposing private account data.',
    'The feature should connect back to trade records whenever the user needs evidence.',
    'It should also connect to analytics when the user wants to move from one example to a broader pattern.',
    'If the user is reviewing mistakes, the page should help name the mistake clearly.',
    'If the user is reviewing strengths, the page should help identify what should be repeated.',
    'Good documentation should explain the purpose, the inputs, the outputs and the review habit.',
    'Inputs are the records, filters, notes or labels the user provides.',
    'Outputs are the insights, summaries or next actions the user gets back.',
    'The review habit is the repeatable routine that makes the feature valuable over time.',
    'The module should avoid unnecessary complexity and keep the main workflow obvious.',
    'A new user should understand the page without needing private support messages.',
    'An experienced user should be able to scan the page and move quickly.',
    'The documentation should make clear that Entrack helps review trading behavior, not guarantee profits.',
    'Past performance should be treated as learning material rather than a promise of future results.',
    'The page should never ask users to paste passwords, recovery codes, API secrets or private keys into normal notes.',
    'Sensitive connection details should be handled only by secure product flows, not by documentation examples.',
    'User-facing examples should use generic sample data and avoid real personal information.',
    'When a module depends on imported data, users should still verify that records are mapped correctly.',
    'When a module depends on manual notes, users should write concise, honest and consistent context.',
    'The strongest workflow is simple: capture data, review behavior, find the pattern and decide one improvement.',
    'This page should make that workflow easier to repeat.',
    'It should also help users understand how the module supports dashboard summaries and deeper review pages.',
    'If something looks wrong, the user should know which module to inspect next.',
    'If something looks useful, the user should know how to save that lesson for the next session.'
  ],
  privacy: 'Privacy note: keep passwords, API keys, access tokens, recovery phrases, broker secrets and personal identity documents out of notes, examples and visible documentation.'
}));
