ALTER TABLE app_auth.users
  ADD COLUMN IF NOT EXISTS google_id TEXT,
  ADD COLUMN IF NOT EXISTS auth_provider TEXT NOT NULL DEFAULT 'local',
  ADD COLUMN IF NOT EXISTS profile_picture TEXT;

ALTER TABLE app_auth.users
  ALTER COLUMN password DROP NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS users_google_id_unique
  ON app_auth.users(google_id)
  WHERE google_id IS NOT NULL AND status <> 'deleted';

CREATE TABLE IF NOT EXISTS app_auth.oauth_login_codes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES app_auth.users(id) ON DELETE CASCADE,
  code_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS oauth_login_codes_active_idx
  ON app_auth.oauth_login_codes(code_hash)
  WHERE used_at IS NULL;
