ALTER TABLE mt5.accounts
  ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_sync_status TEXT,
  ADD COLUMN IF NOT EXISTS last_sync_error TEXT;

CREATE TABLE IF NOT EXISTS mt5.sync_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES app_auth.users(id) ON DELETE CASCADE,
  mt5_account_id INTEGER NOT NULL REFERENCES mt5.accounts(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'queued',
  requested_by TEXT NOT NULL DEFAULT 'manual',
  worker_id TEXT,
  progress_status TEXT,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT sync_jobs_status_check CHECK (status IN ('queued', 'running', 'success', 'failed')),
  CONSTRAINT sync_jobs_requested_by_check CHECK (requested_by IN ('manual', 'scheduled'))
);

CREATE INDEX IF NOT EXISTS sync_jobs_claim_idx
  ON mt5.sync_jobs(status, created_at)
  WHERE status = 'queued';

CREATE INDEX IF NOT EXISTS sync_jobs_user_created_idx
  ON mt5.sync_jobs(user_id, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS sync_jobs_one_active_account_idx
  ON mt5.sync_jobs(mt5_account_id)
  WHERE status IN ('queued', 'running');
