CREATE SCHEMA IF NOT EXISTS app_auth;
CREATE SCHEMA IF NOT EXISTS app;
CREATE SCHEMA IF NOT EXISTS trading;
CREATE SCHEMA IF NOT EXISTS mt5;
CREATE SCHEMA IF NOT EXISTS system;

CREATE TABLE IF NOT EXISTS app_auth.users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL,
  phone TEXT NOT NULL DEFAULT '',
  password TEXT NOT NULL,
  preferred_currency VARCHAR(10) DEFAULT 'USD',
  is_deleted BOOLEAN DEFAULT false,
  reset_token TEXT,
  reset_token_expiry TIMESTAMP,
  name TEXT,
  email_normalized TEXT,
  email_original TEXT,
  password_hash TEXT,
  mobile_normalized TEXT,
  mobile_verified_at TIMESTAMPTZ,
  email_verified_at TIMESTAMPTZ,
  account_type TEXT NOT NULL DEFAULT 'manual',
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  last_login_at TIMESTAMPTZ,
  CONSTRAINT users_status_check CHECK (status IN ('active', 'suspended', 'deleted'))
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_normalized_unique
  ON app_auth.users(email_normalized)
  WHERE status <> 'deleted' AND email_normalized IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS users_mobile_normalized_unique
  ON app_auth.users(mobile_normalized)
  WHERE mobile_normalized IS NOT NULL AND status <> 'deleted';

CREATE INDEX IF NOT EXISTS users_status_idx ON app_auth.users(status);

INSERT INTO app_auth.users (
  id,
  first_name,
  last_name,
  email,
  phone,
  password,
  preferred_currency,
  is_deleted,
  reset_token,
  reset_token_expiry,
  name,
  email_normalized,
  email_original,
  password_hash,
  mobile_normalized,
  mobile_verified_at,
  email_verified_at,
  status,
  created_at,
  updated_at,
  last_login_at
)
SELECT
  "ID",
  "firstName",
  "lastName",
  "email",
  "phone",
  "password",
  preferred_currency,
  COALESCE("isDeleted", false),
  reset_token,
  reset_token_expiry,
  name,
  email_normalized,
  email_original,
  password_hash,
  mobile_normalized,
  mobile_verified_at,
  email_verified_at,
  COALESCE(status, CASE WHEN COALESCE("isDeleted", false) THEN 'deleted' ELSE 'active' END),
  COALESCE(created_at, "createdAt", NOW()),
  COALESCE(updated_at, "createdAt", NOW()),
  last_login_at
FROM public."user"
ON CONFLICT (id) DO UPDATE SET
  first_name = EXCLUDED.first_name,
  last_name = EXCLUDED.last_name,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  password = EXCLUDED.password,
  preferred_currency = EXCLUDED.preferred_currency,
  is_deleted = EXCLUDED.is_deleted,
  reset_token = EXCLUDED.reset_token,
  reset_token_expiry = EXCLUDED.reset_token_expiry,
  name = EXCLUDED.name,
  email_normalized = EXCLUDED.email_normalized,
  email_original = EXCLUDED.email_original,
  password_hash = EXCLUDED.password_hash,
  mobile_normalized = EXCLUDED.mobile_normalized,
  mobile_verified_at = EXCLUDED.mobile_verified_at,
  email_verified_at = EXCLUDED.email_verified_at,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at,
  last_login_at = EXCLUDED.last_login_at;

CREATE TABLE IF NOT EXISTS app_auth.refresh_tokens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES app_auth.users(id) ON DELETE CASCADE,
  token TEXT NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  token_hash TEXT,
  revoked_at TIMESTAMPTZ,
  user_agent TEXT,
  ip_address TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS refresh_tokens_token_hash_unique
  ON app_auth.refresh_tokens(token_hash)
  WHERE token_hash IS NOT NULL;

CREATE INDEX IF NOT EXISTS refresh_tokens_user_active_idx
  ON app_auth.refresh_tokens(user_id)
  WHERE revoked_at IS NULL;

INSERT INTO app_auth.refresh_tokens (
  id, user_id, token, expires_at, created_at, token_hash, revoked_at, user_agent, ip_address
)
SELECT id, user_id, token, expires_at, created_at, token_hash, revoked_at, user_agent, ip_address
FROM public.refresh_tokens
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  token = EXCLUDED.token,
  expires_at = EXCLUDED.expires_at,
  created_at = EXCLUDED.created_at,
  token_hash = EXCLUDED.token_hash,
  revoked_at = EXCLUDED.revoked_at,
  user_agent = EXCLUDED.user_agent,
  ip_address = EXCLUDED.ip_address;

CREATE TABLE IF NOT EXISTS app_auth.email_verifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email_normalized TEXT NOT NULL UNIQUE,
  email_original TEXT NOT NULL,
  mobile_normalized TEXT,
  password_hash TEXT NOT NULL,
  verification_token_hash TEXT NOT NULL UNIQUE,
  verification_expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT email_verifications_name_check CHECK (char_length(name) >= 2 AND char_length(name) <= 80)
);

CREATE INDEX IF NOT EXISTS email_verifications_expires_idx
  ON app_auth.email_verifications(verification_expires_at);

INSERT INTO app_auth.email_verifications (
  id,
  name,
  email_normalized,
  email_original,
  mobile_normalized,
  password_hash,
  verification_token_hash,
  verification_expires_at,
  created_at
)
SELECT
  id,
  name,
  email_normalized,
  email_original,
  mobile_normalized,
  password_hash,
  verification_token_hash,
  verification_expires_at,
  created_at
FROM public.pending_users
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  email_normalized = EXCLUDED.email_normalized,
  email_original = EXCLUDED.email_original,
  mobile_normalized = EXCLUDED.mobile_normalized,
  password_hash = EXCLUDED.password_hash,
  verification_token_hash = EXCLUDED.verification_token_hash,
  verification_expires_at = EXCLUDED.verification_expires_at,
  created_at = EXCLUDED.created_at;

CREATE TABLE IF NOT EXISTS app_auth.password_resets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id INTEGER NOT NULL REFERENCES app_auth.users(id) ON DELETE CASCADE,
  token_hash TEXT UNIQUE,
  otp_hash TEXT,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS password_resets_otp_hash_unique
  ON app_auth.password_resets(otp_hash)
  WHERE otp_hash IS NOT NULL;

CREATE INDEX IF NOT EXISTS password_resets_expiry_idx ON app_auth.password_resets(expires_at);
CREATE INDEX IF NOT EXISTS password_resets_user_idx ON app_auth.password_resets(user_id);

INSERT INTO app_auth.password_resets (id, user_id, token_hash, expires_at, used_at, created_at)
SELECT id, user_id, token_hash, expires_at, used_at, created_at
FROM public.password_reset_tokens
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  token_hash = EXCLUDED.token_hash,
  expires_at = EXCLUDED.expires_at,
  used_at = EXCLUDED.used_at,
  created_at = EXCLUDED.created_at;

CREATE TABLE IF NOT EXISTS app.user_settings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES app_auth.users(id) ON DELETE CASCADE,
  settings JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id)
);

INSERT INTO app.user_settings (id, user_id, settings, created_at, updated_at)
SELECT id, user_id, COALESCE(settings, '{}'::jsonb), created_at, updated_at
FROM public.user_settings
WHERE EXISTS (
  SELECT 1
  FROM app_auth.users u
  WHERE u.id = public.user_settings.user_id
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  settings = EXCLUDED.settings,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

CREATE TABLE IF NOT EXISTS trading.manual_trades (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES app_auth.users(id) ON DELETE CASCADE,
  symbol VARCHAR(50),
  trade_type VARCHAR(20),
  price NUMERIC,
  category VARCHAR(64),
  exit_price NUMERIC,
  strategy VARCHAR(120),
  quantity NUMERIC,
  pnl NUMERIC,
  notes TEXT,
  screenshots TEXT,
  timestamp TIMESTAMP,
  unique_id TEXT,
  open_timestamp BIGINT,
  close_timestamp BIGINT,
  is_breakeven BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS manual_trades_user_id_idx ON trading.manual_trades(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS manual_trades_user_unique_id_unique
  ON trading.manual_trades(user_id, unique_id)
  WHERE unique_id IS NOT NULL;

INSERT INTO trading.manual_trades (
  id,
  user_id,
  symbol,
  trade_type,
  price,
  category,
  exit_price,
  strategy,
  quantity,
  pnl,
  notes,
  screenshots,
  timestamp,
  unique_id,
  open_timestamp,
  close_timestamp,
  is_breakeven
)
SELECT
  "ID",
  user_id,
  symbol,
  trade_type,
  price,
  category,
  exit_price,
  strategy,
  quantity,
  pnl,
  notes,
  screenshots,
  timestamp,
  unique_id,
  open_timestamp,
  close_timestamp,
  is_breakeven
FROM public.trades
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  symbol = EXCLUDED.symbol,
  trade_type = EXCLUDED.trade_type,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  exit_price = EXCLUDED.exit_price,
  strategy = EXCLUDED.strategy,
  quantity = EXCLUDED.quantity,
  pnl = EXCLUDED.pnl,
  notes = EXCLUDED.notes,
  screenshots = EXCLUDED.screenshots,
  timestamp = EXCLUDED.timestamp,
  unique_id = EXCLUDED.unique_id,
  open_timestamp = EXCLUDED.open_timestamp,
  close_timestamp = EXCLUDED.close_timestamp,
  is_breakeven = EXCLUDED.is_breakeven;

CREATE TABLE IF NOT EXISTS mt5.accounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES app_auth.users(id) ON DELETE CASCADE,
  broker_name VARCHAR(120) NOT NULL,
  account_id BIGINT NOT NULL,
  server_name VARCHAR(120) NOT NULL,
  investor_password VARCHAR(255),
  connection_status VARCHAR(50) DEFAULT 'disconnected',
  last_connected TIMESTAMP,
  balance NUMERIC DEFAULT 0,
  default_currency VARCHAR(10) DEFAULT 'USD',
  balance_change NUMERIC,
  temporary_currency VARCHAR(10),
  login_id TEXT,
  broker_server TEXT,
  instance_key TEXT,
  status TEXT DEFAULT 'connected',
  connected_at TIMESTAMPTZ,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS mt5_accounts_account_id_key ON mt5.accounts(account_id);
CREATE UNIQUE INDEX IF NOT EXISTS mt5_accounts_instance_key_idx
  ON mt5.accounts(instance_key)
  WHERE instance_key IS NOT NULL;

INSERT INTO mt5.accounts (
  id,
  user_id,
  broker_name,
  account_id,
  server_name,
  investor_password,
  connection_status,
  last_connected,
  created_at,
  updated_at,
  balance,
  default_currency,
  balance_change,
  temporary_currency,
  login_id,
  broker_server,
  instance_key,
  status,
  connected_at
)
SELECT
  id,
  user_id,
  broker_name,
  account_id,
  server_name,
  investor_password,
  connection_status,
  last_connected,
  created_at,
  updated_at,
  balance,
  default_currency,
  balance_change,
  temporary_currency,
  login_id,
  broker_server,
  instance_key,
  status,
  connected_at
FROM public.mt5_accounts
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  broker_name = EXCLUDED.broker_name,
  account_id = EXCLUDED.account_id,
  server_name = EXCLUDED.server_name,
  investor_password = EXCLUDED.investor_password,
  connection_status = EXCLUDED.connection_status,
  last_connected = EXCLUDED.last_connected,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at,
  balance = EXCLUDED.balance,
  default_currency = EXCLUDED.default_currency,
  balance_change = EXCLUDED.balance_change,
  temporary_currency = EXCLUDED.temporary_currency,
  login_id = EXCLUDED.login_id,
  broker_server = EXCLUDED.broker_server,
  instance_key = EXCLUDED.instance_key,
  status = EXCLUDED.status,
  connected_at = EXCLUDED.connected_at;

CREATE TABLE IF NOT EXISTS trading.api_trades (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES app_auth.users(id) ON DELETE CASCADE,
  account_id BIGINT NOT NULL,
  platform VARCHAR(20) DEFAULT 'MT5',
  symbol VARCHAR(50) NOT NULL,
  trade_type VARCHAR(20) NOT NULL,
  quantity NUMERIC NOT NULL,
  price NUMERIC NOT NULL,
  exit_price NUMERIC NOT NULL,
  pnl NUMERIC DEFAULT 0,
  timestamp TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ticket BIGINT,
  notes TEXT,
  screenshots JSONB,
  strategy VARCHAR(120),
  unique_id TEXT,
  percent_change NUMERIC,
  open_timestamp BIGINT,
  close_timestamp BIGINT,
  is_breakeven BOOLEAN NOT NULL DEFAULT false,
  category TEXT,
  symbol_path TEXT,
  symbol_description TEXT,
  CONSTRAINT api_trades_account_fk FOREIGN KEY (account_id) REFERENCES mt5.accounts(account_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS api_trades_user_id_idx ON trading.api_trades(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS api_trades_ticket_unique ON trading.api_trades(ticket);

INSERT INTO trading.api_trades (
  id,
  user_id,
  account_id,
  platform,
  symbol,
  trade_type,
  quantity,
  price,
  exit_price,
  pnl,
  timestamp,
  created_at,
  ticket,
  notes,
  screenshots,
  strategy,
  unique_id,
  percent_change,
  open_timestamp,
  close_timestamp,
  is_breakeven,
  category,
  symbol_path,
  symbol_description
)
SELECT
  id,
  user_id,
  account_id,
  platform,
  symbol,
  trade_type,
  quantity,
  price,
  exit_price,
  pnl,
  timestamp,
  created_at,
  ticket,
  notes,
  screenshots,
  strategy,
  unique_id,
  percent_change,
  open_timestamp,
  close_timestamp,
  is_breakeven,
  category,
  symbol_path,
  symbol_description
FROM public.api_trades
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  account_id = EXCLUDED.account_id,
  platform = EXCLUDED.platform,
  symbol = EXCLUDED.symbol,
  trade_type = EXCLUDED.trade_type,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  exit_price = EXCLUDED.exit_price,
  pnl = EXCLUDED.pnl,
  timestamp = EXCLUDED.timestamp,
  created_at = EXCLUDED.created_at,
  ticket = EXCLUDED.ticket,
  notes = EXCLUDED.notes,
  screenshots = EXCLUDED.screenshots,
  strategy = EXCLUDED.strategy,
  unique_id = EXCLUDED.unique_id,
  percent_change = EXCLUDED.percent_change,
  open_timestamp = EXCLUDED.open_timestamp,
  close_timestamp = EXCLUDED.close_timestamp,
  is_breakeven = EXCLUDED.is_breakeven,
  category = EXCLUDED.category,
  symbol_path = EXCLUDED.symbol_path,
  symbol_description = EXCLUDED.symbol_description;

CREATE TABLE IF NOT EXISTS mt5.connection_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES app_auth.users(id) ON DELETE CASCADE,
  login_id TEXT NOT NULL,
  broker_server TEXT NOT NULL,
  encrypted_password TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT connection_requests_status_check CHECK (status IN (
    'pending',
    'connecting',
    'creating_terminal',
    'launching_terminal',
    'applying_ea',
    'connected',
    'failed'
  ))
);

CREATE INDEX IF NOT EXISTS connection_requests_user_created_idx
  ON mt5.connection_requests(user_id, created_at DESC);

INSERT INTO mt5.connection_requests (
  id,
  user_id,
  login_id,
  broker_server,
  encrypted_password,
  status,
  error_message,
  created_at,
  updated_at
)
SELECT id, user_id, login_id, broker_server, encrypted_password, status, error_message, created_at, updated_at
FROM public.mt5_connection_requests
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  login_id = EXCLUDED.login_id,
  broker_server = EXCLUDED.broker_server,
  encrypted_password = EXCLUDED.encrypted_password,
  status = EXCLUDED.status,
  error_message = EXCLUDED.error_message,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

CREATE TABLE IF NOT EXISTS mt5.vps_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id BIGINT NOT NULL REFERENCES mt5.connection_requests(id) ON DELETE CASCADE,
  job_type TEXT NOT NULL DEFAULT 'CREATE_MT5_INSTANCE',
  status TEXT NOT NULL DEFAULT 'pending',
  instance_key TEXT NOT NULL UNIQUE,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT vps_jobs_type_check CHECK (job_type IN ('CREATE_MT5_INSTANCE')),
  CONSTRAINT vps_jobs_status_check CHECK (status IN ('pending', 'claimed', 'running', 'completed', 'failed'))
);

CREATE INDEX IF NOT EXISTS vps_jobs_pending_idx
  ON mt5.vps_jobs(status, created_at)
  WHERE status = 'pending';

INSERT INTO mt5.vps_jobs (
  id,
  request_id,
  job_type,
  status,
  instance_key,
  error_message,
  created_at,
  updated_at
)
SELECT id, request_id, job_type, status, instance_key, error_message, created_at, updated_at
FROM public.mt5_vps_jobs
ON CONFLICT (id) DO UPDATE SET
  request_id = EXCLUDED.request_id,
  job_type = EXCLUDED.job_type,
  status = EXCLUDED.status,
  instance_key = EXCLUDED.instance_key,
  error_message = EXCLUDED.error_message,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

CREATE TABLE IF NOT EXISTS system.admin_integrations (
  id TEXT PRIMARY KEY,
  provider TEXT NOT NULL,
  account_id BIGINT,
  is_demo BOOLEAN,
  access_token TEXT,
  refresh_token TEXT,
  expires_at BIGINT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO system.admin_integrations (
  id, provider, account_id, is_demo, access_token, refresh_token, expires_at, updated_at
)
SELECT id, provider, account_id, is_demo, access_token, refresh_token, expires_at, updated_at
FROM public.admin_integrations
ON CONFLICT (id) DO UPDATE SET
  provider = EXCLUDED.provider,
  account_id = EXCLUDED.account_id,
  is_demo = EXCLUDED.is_demo,
  access_token = EXCLUDED.access_token,
  refresh_token = EXCLUDED.refresh_token,
  expires_at = EXCLUDED.expires_at,
  updated_at = EXCLUDED.updated_at;

CREATE TABLE IF NOT EXISTS system.schema_migrations (
  id TEXT PRIMARY KEY,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO system.schema_migrations (id, applied_at)
SELECT id, applied_at
FROM public.schema_migrations
ON CONFLICT (id) DO UPDATE SET applied_at = EXCLUDED.applied_at;

SELECT setval(pg_get_serial_sequence('app_auth.users', 'id'), COALESCE((SELECT MAX(id) FROM app_auth.users), 1), true);
SELECT setval(pg_get_serial_sequence('app_auth.refresh_tokens', 'id'), COALESCE((SELECT MAX(id) FROM app_auth.refresh_tokens), 1), true);
SELECT setval(pg_get_serial_sequence('app.user_settings', 'id'), COALESCE((SELECT MAX(id) FROM app.user_settings), 1), true);
SELECT setval(pg_get_serial_sequence('trading.manual_trades', 'id'), COALESCE((SELECT MAX(id) FROM trading.manual_trades), 1), true);
SELECT setval(pg_get_serial_sequence('trading.api_trades', 'id'), COALESCE((SELECT MAX(id) FROM trading.api_trades), 1), true);
SELECT setval(pg_get_serial_sequence('mt5.accounts', 'id'), COALESCE((SELECT MAX(id) FROM mt5.accounts), 1), true);
SELECT setval(pg_get_serial_sequence('mt5.connection_requests', 'id'), COALESCE((SELECT MAX(id) FROM mt5.connection_requests), 1), true);
SELECT setval(pg_get_serial_sequence('mt5.vps_jobs', 'id'), COALESCE((SELECT MAX(id) FROM mt5.vps_jobs), 1), true);
